(forward-char)
(backward-char)
(insert 65)
(insert (make-string 66 2))
(insert "foo")
(setf (qreg "A") "foo")
(delete-char)
(delete-char -2)
(delete-char (- (qreg "A")))
(setf (qreg "A") 42)
(funcall (qreg "A"))
(insert (qreg "A"))
(incf (qreg "A"))
(goto-char (point-min))
(goto-char (point-max))
(kill-line)
(kill-region (point-min) (point-max))
(setf (qreg "A") (buffer-substring (point-max) (point-min)))
(insert (format "%s" (qreg "B")))
(message "%s" 42)
(loop repeat 5 do (delete-char))
(loop (backward-char) (when (plusp (qreg "A")) (return)) (forward-char))
(when (zerop (qreg "A")) (funcall (qreg "B")))
(search-forward "foo")
(push (qreg "A") *pdl*)
(setf (qreg "A") (pop *pdl*))
(push (qreg "B") *pdl*)
(setf (qreg "B") 42)
(setf (qreg "B") (pop *pdl*))
