name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        if: ${{runner.os == 'Linux'}}
        run: sudo apt-get install emacs
      - name: Test
        run: cd test && sh run.sh
